### ISSUE TITLE
(question) Heroku and Redis

### ISSUE THREAD

**Issue by Serif773** [authorizerdev/authorizer#127]
If I use heroku, and don't use Redis, would users be logged out after 27 hours?(average heroku restart time is 27hours).
In short, is Redis optional? And if I don't use redis on heroku would I users be logged out?

Also, additionally, how do I increase the expiry time of jwt token? I see one reference to `expires_at: Int64`. Do I need to change something over here?

**Comment by lakhansamani** [comment]
@Serif773 Redis is optional, but not recommended for production.
User will not logged out as and when server restarts as sessions are stored in memory till that.

There are 2 tokens
-> Refresh token expires in 90 days (though rotated with each token request, so that there are less chances of token being exposed)
-> Also refresh token is validated with finger print
-> Access token expires in 15 min (silent refresh is done in FE library to get new access token)

**Comment by lakhansamani** [comment]
@Serif773 I haven't done benchmarking / stress testing for heroku,

But we can do it using 
https://github.com/tsenart/vegeta

Also, there are benchmarks available for the Go Gin server which we are using (https://github.com/gin-gonic/gin#benchmarks)
Though numbers will change on heroku

**Comment by lakhansamani** [comment]
@Serif773 are we good to close this issue?

**Comment by Serif773** [comment]
> @Serif773 are we good to close this issue?

Yes
