### ISSUE TITLE
Redirect Issue

### ISSUE THREAD

**Issue by candidexmedia** [authorizerdev/authorizer#213]
**Version:** 0.38.0

**Describe the bug**

I was testing out authorizer.dev on a test static site as well as via [your js demo](https://ybped.csb.app/), and noticed some issues with the `redirectURL`. On my website, I set the `redirectURL` to window.location.origin (as the docs indicate). However, it redirects the user to the home page (instead of the page where the login is set), and when I try to go to the page, it brings me back to the home page.

On [your js demo](https://ybped.csb.app/), there appears to be an endless loop of redirects between the authorizer instance and the page that had the code (see video below). I noticed the same issue when I changed the `redirectURL` for my site to the URL's page.

**Steps To Reproduce**

1. Head to https://ybped.csb.app/
2. Create an account

**Expected behavior**

Redirected to the page where the user logs in.

**Screenshots**

https://user-images.githubusercontent.com/95003834/184574579-3c598097-8483-4a31-b3fc-39e67270bbf5.mp4

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Firefox
- Version 103.0.2

**Comment by lakhansamani** [comment]
@candidexmedia thank you for sharing this,
This is actually not a bug,
Firefox does not allow cross-browser cookies for security reasons
Because of the different domains here, it is breaking on firefox you can try the same demo on chrome and it will work. Soon chrome is also going to end this support so you will always have to configure right domains :-) 
Codesandbox domain and authorizer instance domain name is different and cookies validation fails for that on authorizer domain.

In an ideal scenario, the authorizer domain and application domain would be identical so this will not create problems.
Just for testing purpose you can try following URL on your firefox and it will work

https://demo.authorizer.dev/app/?redirectURL=https://demo.authorizer.dev/app

**Comment by candidexmedia** [comment]
I see, makes sense! Thank you for explaining. 

I'll create a subdomain for my Authorizer deployment.

Also, it is normal for unregistered users to see a flash of the page that's meant to be password-protected before being redirected?

https://user-images.githubusercontent.com/95003834/184586444-b7721690-58db-4621-ba76-f7b9446ef7cb.mp4

**Comment by lakhansamani** [comment]
@candidexmedia I would create a public page and then redirect users based on application needs. But you can always create a condition in CSS & JS which renders based on the state and till that show a loader. 

Example of how we render the logout button here https://github.com/authorizerdev/examples/blob/main/with-vanilla-js/index.html#L35
