### ISSUE TITLE
Add ability to sign up via magic link

### ISSUE THREAD

**Issue by lakhansamani** [authorizerdev/authorizer#48]
**Feature Description**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lakhansamani** [comment]
Resolved #65

**Comment by shiftlabs1** [comment]
@lakhansamani , sorry to drop this here instead of creating a new item. I am trying to make sense of the magic link flow. When a user clicks on the link in their email , what happens next ? what authorizer function do we call on our application to verify the incoming link ? Does it have a token attached? are we supposed to call verifyEmail and pass a token parameters from the URl like we do in the SIgn up Flow ? There is no where in the documentation (or any of the youtube videos)  explaining this bit
